backend:
  name: git-gateway
  branch: main

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

publish_mode: editorial_workflow

collections:
  - name: "updates"
    label: "Updates"
    folder: "updates"
    create: true
    slug: "{{slug}}"
    extension: "html"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Summary", name: "summary", widget: "text", required: false }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Main Pages"
    files:
      - label: "Homepage"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Our Story"
        name: "story"
        file: "story.html"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
